# Generated by Django 3.1.5 on 2021-01-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='repo',
            field=models.URLField(blank=True),
        ),
    ]
