# Generated by Django 3.1.5 on 2021-01-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
